apiVersion: apps/v1
kind: Deployment
metadata:
  name: cn-demo-dpl
  labels:
    app: website
    version: v1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  revisionHistoryLimit: 6
  paused: false  
  minReadySeconds: 10
  selector:
    matchLabels: 
      tier: frontend
  template:
    metadata:
      name: cn-demo-pod
      labels:
        app: website
        tier: frontend
        version: v1
    spec:
      containers:
        - name: cn-demo
          image: smichard/cn-app:v2
          ports:
            - containerPort: 80
              protocol: TCP
