resource_types:
- name: slack_notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: app_sources
  type: git
  source:
    uri: http://127.0.0.1:30080/root/cloud_foundry_demo.git
    branch: master
  check_every: 10s

- name: cloud_foundry
  type: cf
  source:
    api: {{cf_pws_dellemc_api}}
    username: {{cf_pws_dellemc_user}}
    password: {{cf_pws_dellemc_password}}
    organization: {{cf_pws_dellemc_org}}
    space: {{cf_pws_dellemc_space_production}}
    skip_cert_check: false

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

- name: version
  type: semver
  source:
    uri: http://127.0.0.1:30080/root/cloud_foundry_demo.git
    branch: version
    username: root
    password: testtest
    file: version
    driver: git
    initial_version: 0.5.0

- name: minio_target
  type: s3
  source:
    endpoint: http://192.168.58.6:9000/minio/releases/
    bucket: releases
    regexp: iot_demo-(.*)-(.*).tar.gz
    access_key_id: admin
    secret_access_key: Password1!

jobs:
  - name: test-app
    public: true

    serial: true
    plan:
      - get: app_sources
        trigger: true
      - task: unit
        file: app_sources/ci/tasks/unit.yml

  - name: deploy-app
    public: true
    serial: true
    plan:
    - get: app_sources
      passed: [ test-app ]
      version: every
      trigger: true
    - put: cloud_foundry
      params:
        path: app_sources/website/
        manifest: app_sources/website/manifest.yml
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Prod: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. Check the current development state at:
            https://sensor-cloud.cfapps.io/
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            Prod: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID

  - name: minio-backup
    public: true
    serial: true
    plan:
    - get: version
      trigger: false
    - get: app_sources
      trigger: true
      passed: [ deploy-app ]
    - task: create-artifact
      file: app_sources/ci/tasks/create_artifact.yml
    - put: minio_target
      params:
        file: ./artifact/iot_demo-*-*.tar.gz
        acl: public-read

  - name: bump-version-minor
    public: true
    plan:
      - aggregate:
        - get:  app_sources
          passed: [ minio-backup ]
          trigger: true
        - get: version
          trigger: false
        - put: version
          params: {bump: minor}
