apiVersion: v1
kind: Service
metadata:
  name: cn-demo-srv
  labels:
    app: website
    tier: frontend
    version: v1
spec:
  selector:  
    app: website
    tier: frontend
    version: v1
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
  externalIPs:
    - 192.168.99.100